### ISSUE TITLE
Critical vuln in follow-redirects

### ISSUE THREAD

**Issue by benvand** [gov-cy/dsf-design-system#61]
Percy Script depenedency in package.json file hads sub-sub dependency on `follow-redirects` package.
This package has a sever security vulnerability.
Percy/script is deprecated https://www.npmjs.com/package/@percy/script?activeTab=readme

In favour of [percy-snapshot](https://docs.percy.io/docs/percy-snapshot)

We need to iinstall percy using percy-snapshot and potentially update commands to use this package.

**Comment by cevangelougovcy** [comment]
I'll have a look on migrating to [percy CLI](https://docs.percy.io/docs/migrating-to-percy-cli) which uses the `percy-snapshot`
